FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD maventest.jar /opt/maventest/
EXPOSE 8080
WORKDIR /opt/maventest/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "maventest.jar"]
